application: appspotname
version: 1
runtime: go
api_version: go1

handlers:
- url: /app
  static_dir: app

- url: /(js/.*\.js)
  static_files: \1
  upload: js/.*\.js

- url: /(css/.*\.css)
  static_files: \1
  upload: css/.*\.css

- url: /api/.*
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^\.git/.*
- .gitignore
- .git
- ^(.*/)?.*/.git/.*$
- ^(.*/)?.*/assets/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/test/.*$
- ^(.*/)?.*/templates/.*$
- ^(.*/)?.*/node_modules/.*$
- ^(assets/.*)
- ^(build/.*)
- ^(test/.*)
- ^(templates/.*)
- ^(node_modules/.*)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
